travis_fold:start:system_info
Build language: python
travis_fold:end:system_info

.FF
======================================================================
FAIL: test.test_1({'a': 1, 'b': ['two', 'three', 'four'], 'c': {'foo': 1, 'bar': 2}}, 2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aubergenie/temp/venv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/aubergenie/temp/test.py", line 15, in _test_1_subtest
    assert dct['a'] == val
AssertionError

======================================================================
FAIL: test.test_2({'b': 2, 'a': 1},)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aubergenie/temp/venv/lib/python3.8/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/aubergenie/temp/test.py", line 31, in _test_2_subtest
    assert False
AssertionError

----------------------------------------------------------------------
Ran 3 tests in 0.003s

FAILED (failures=2)